site_name: ReadShade
repo_name: ReadShade Repository
repo_url: https://github.com/papadanku/ReadShade
copyright: Copyright &copy; 2024

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

plugins:
  - offline
  - search

nav:
  - Home:
    - index.md
    - technical.md
  - ReShade:
    - reshade/reshadeversions.md
    - reshade/windpi.md
    - reshade/dlssframegen.md
    - reshade/posteffects.md
  - Add-Ons:
    - addons/placeholder.md
  - Hardware:
    - hardware/placeholder.md
  - Emulators:
    - emulators/pcsx2.md
  - Games:
    - games/placeholder.md
  - Depth3D:
    - Add-ons:
      - depth3d/basicguides/genericdepth.md
      - depth3d/basicguides/shadertoggler.md
      - depth3d/basicguides/rest.md
    - Hardware:
      - depth3d/hardwareguides/viture.md
      - depth3d/hardwareguides/sr.md
